
CREATE TABLE `price_adjustment_strategy` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `strategy_name` varchar(256) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '策略名称',
  `strategy_desc` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '策略描述',
  `biz_line_id` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '业务线id',
  `strategy_type` int(11) NOT NULL DEFAULT '0' COMMENT '策略模板，1-平台加减价，2-折上折',
  `start_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
  `end_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '结束时间',
  `period_time` varchar(2000) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '周期',
  `status` tinyint(2) NOT NULL DEFAULT '1' COMMENT '策略状态，1-上线，2-下线',
  `audit_status` tinyint(2) NOT NULL DEFAULT '1' COMMENT '审核状态，1-待审核，2-审核通过，3-审核驳回',
  `creator` varchar(100) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '创建人',
  `budget_id` varchar(100) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '预算编号',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int(11) NOT NULL DEFAULT '1' COMMENT '乐观锁版本号',
  `ctrl_type` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '管控类型',
  `ctrl_count` int(11) NOT NULL DEFAULT '0' COMMENT '管控数量',
  `crowd` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT 'ALL' COMMENT '人群',
  `times_limit` int(11) NOT NULL DEFAULT '-1' COMMENT '最大次数限制，-1表示不限制',
  `times_limit_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '次数限制类型，1表示活动期内，2表示每天',
  `quantity_limit` double NOT NULL DEFAULT '-1' COMMENT '升数限制，-1表示不限制',
  `quantity_limit_type` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '-1' COMMENT '数量限制类型：升数/金额',
  `extra` varchar(2048) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '扩展字段',
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE = InnoDB AUTO_INCREMENT = 0 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin COMMENT = '调价策略表'


CREATE TABLE `price_adjustment_strategy_detail` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `strategy_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '策略id',
  `strategy_type` int(11) NOT NULL DEFAULT '0' COMMENT '策略模板（冗余），1-平台加减价，2-折上折, 3-订单维度的联合满减',
  `adjust_value` decimal(15, 4) NOT NULL DEFAULT '0.0000' COMMENT '调整的值，加减价的数值，或折上折的折扣值，或订单维度联合满减的数值',
  `start_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间（冗余）',
  `end_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '结束时间（冗余）',
  `store_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '门店id',
  `channel_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '渠道id',
  `item_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '商品id',
  `operator` varchar(100) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '操作人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `pricing_type` int(11) NOT NULL DEFAULT '1' COMMENT '定价类型（不填默认基础折扣）',
  `discount_value` bigint(20) NOT NULL DEFAULT '10000' COMMENT '当前折扣值',
  `online_price` decimal(15, 4) NOT NULL DEFAULT '-1.0000' COMMENT '当前线上价格',
  `strategy_price` decimal(15, 4) NOT NULL DEFAULT '-1.0000' COMMENT '策略后价格',
  `store_name` varchar(100) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '门店名称',
  `satisfy_value` decimal(15, 4) NOT NULL DEFAULT '0.0000' COMMENT '享受优惠需要满足的条件：订单维度的联合满减需要满足的订单金额',
  `merchant_ratio` decimal(8, 4) NOT NULL DEFAULT '9999.0000' COMMENT '商家承担比例（单位%）',
  `city_id` bigint(20) NOT NULL DEFAULT '-1' COMMENT '城市id',
  `extra` varchar(5000) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '扩展字段',
  PRIMARY KEY (`id`),
  KEY `idx_stratedy_id` (`strategy_id`),
  KEY `idx_store` (`store_id`, `start_time`, `end_time`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_store_end` (`store_id`, `end_time`),
  KEY `idx_city_type_time` (`city_id`, `strategy_type`, `end_time`)
) ENGINE = InnoDB AUTO_INCREMENT = 0 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin COMMENT = '调价策略明细表'
